// Both contracts are plain data with no optional dependency behind them, and
// the publish facade below is unconditional so callers never branch on the
// host, so neither carries a feature gate.
pub mod accessibility_publish;
pub mod accessibility_tree;
#[cfg(feature = "activation")]
pub mod activation;
#[cfg(feature = "window-enum")]
pub mod app_inventory;
pub mod cache_hierarchy;
pub mod chassis_loader;
#[cfg(feature = "chassis-present")]
pub mod chassis_present;
#[cfg(feature = "clipboard")]
pub mod clipboard;
#[cfg(feature = "console-interrupt")]
pub mod console_interrupt;
#[cfg(feature = "console-line-editor")]
pub mod console_line_editor;
#[cfg(all(feature = "window", feature = "input"))]
pub mod control_window;
#[cfg(feature = "current-target-binding")]
pub mod current_target_binding;
#[cfg(feature = "desktop-host")]
pub mod desktop_host;
#[cfg(feature = "entropy")]
pub mod entropy;
#[cfg(feature = "font")]
pub mod font;
#[cfg(feature = "hardware")]
pub mod hardware;
#[cfg(feature = "host-memory")]
pub mod host_memory;
#[cfg(feature = "ime")]
pub mod ime;
#[cfg(feature = "input")]
pub mod input;
#[cfg(feature = "input-inject")]
pub mod input_inject;
#[cfg(feature = "ipc")]
pub mod ipc_transport;
pub mod local_clock;
pub mod native_virtualization;
#[cfg(feature = "network-interfaces")]
pub mod network_interfaces;
pub mod pixel_present;
#[cfg(feature = "process")]
pub mod process;
#[cfg(feature = "process-control")]
pub mod process_control;
pub mod process_conventions;
#[cfg(feature = "process-image")]
pub mod process_image;
#[cfg(feature = "process-metrics")]
pub mod process_metrics;
#[cfg(feature = "process-observation")]
pub mod process_observation;
#[cfg(feature = "process-spawn")]
pub mod process_spawn;
#[cfg(feature = "process-window")]
pub mod process_window;
#[cfg(feature = "processor-affinity")]
pub mod processor_affinity;
pub mod processor_topology;
#[cfg(feature = "pty")]
pub mod pty;
#[cfg(feature = "runtime")]
pub mod runtime;
#[cfg(feature = "shared-memory")]
pub mod shared_memory;
#[cfg(feature = "storage")]
pub mod storage;
#[cfg(feature = "input")]
pub mod terminal_input;
#[cfg(feature = "screenshot")]
pub mod ui_screenshot;
#[cfg(feature = "webview")]
pub mod webview;
#[cfg(feature = "window-enum")]
pub mod window_enumerate;
#[cfg(all(feature = "window", feature = "input", feature = "ime"))]
pub mod window_host;
#[cfg(feature = "window-op")]
pub mod window_op;
#[cfg(all(feature = "window-enum", feature = "window-op", feature = "a11y-tree"))]
pub mod window_placement;
