#!/usr/bin/env bash
# Generate docs/agenterm-cu-verbs.md from the binary's own verb table.
# Source of truth: `agenterm-cu verbs --json` (name, aliases, scope, family,
# summary, usage) plus `agenterm-cu help <verb>` for the reference prose.
# Run from the repository root after `cargo build -p agenterm-cu --bin agenterm-cu`.
set -euo pipefail
CU=${AGENTERM_CU:-agenterm-cu}
OUT=${1:-docs/agenterm-cu-verbs.md}
command -v "$CU" >/dev/null || { echo "gen-cu-verbs-doc: $CU not on PATH" >&2; exit 2; }
"$CU" verbs --json > /tmp/.cu-verbs.$$ 2>/dev/null || { echo "gen-cu-verbs-doc: verbs --json failed" >&2; exit 2; }
trap 'rm -f /tmp/.cu-verbs.$$' EXIT
{
  echo "# agenterm-cu verb reference"
  echo
  echo "Generated by \`scripts/gen-cu-verbs-doc.sh\` from \`agenterm-cu verbs --json\` and"
  echo "\`agenterm-cu help <verb>\`; do not edit by hand. The agent-facing quick guide is"
  echo "\`crates/agenterm-cu/README.md\`; the design authority is \`prd/PRD_02_29_cu_command_surface.md\`."
  echo
  python3 - /tmp/.cu-verbs.$$ <<'PY'
import json, sys, subprocess, os
verbs = json.load(open(sys.argv[1]))
cu = os.environ.get("AGENTERM_CU", "agenterm-cu")
families = []
for v in verbs:
    if v["family"] not in families:
        families.append(v["family"])
print("## Index\n")
print("| verb | scope | family | aliases | summary |")
print("|---|---|---|---|---|")
for v in verbs:
    print(f"| `{v['name']}` | {v.get('grant','')} | {v['family']} | {', '.join('`'+a+'`' for a in v.get('aliases',[])) or '—'} | {v.get('summary','')} |")
for fam in families:
    print(f"\n## {fam}\n")
    for v in [x for x in verbs if x["family"] == fam]:
        print(f"### `{v['name']}`\n")
        if v.get("usage"):
            print("```text")
            print(v["usage"])
            print("```\n")
        ref = subprocess.run([cu, "help", v["name"]], capture_output=True, text=True)
        prose = ref.stderr.strip() or ref.stdout.strip()
        if prose:
            print("```text")
            print(prose)
            print("```\n")
PY
} > "$OUT"
echo "gen-cu-verbs-doc: wrote $OUT ($(wc -l < "$OUT") lines)"
