#!/usr/bin/env bash
# Generate docs/agenterm-cu-verbs.md from the binary's validated projection of
# `crates/agenterm-cu/src/cli/verbs-catalog.json`.
# Run from the repository root after `cargo build -p agenterm-cu --bin agenterm-cu`.
set -euo pipefail
CU=${AGENTERM_CU:-agenterm-cu}
OUT=${1:-docs/agenterm-cu-verbs.md}
command -v "$CU" >/dev/null || { echo "gen-cu-verbs-doc: $CU not on PATH" >&2; exit 2; }
"$CU" verbs --json > /tmp/.cu-verbs.$$ 2>/dev/null || { echo "gen-cu-verbs-doc: verbs --json failed" >&2; exit 2; }
TMP=$(mktemp "${OUT}.tmp.XXXXXX") || { echo "gen-cu-verbs-doc: cannot stage $OUT" >&2; exit 2; }
trap 'rm -f /tmp/.cu-verbs.$$ "$TMP"' EXIT
{
  echo "# agenterm-cu verb reference"
  echo
  echo "Generated by \`scripts/gen-cu-verbs-doc.sh\` from \`agenterm-cu verbs --json\` and"
  echo "\`agenterm-cu help <verb>\`; do not edit by hand. The agent-facing quick guide is"
  echo "\`crates/agenterm-cu/README.md\`; the design authority is \`prd/PRD_02_29_cu_command_surface.md\`."
  echo
  python3 - /tmp/.cu-verbs.$$ <<'PY'
import json, sys, subprocess, os
verbs = json.load(open(sys.argv[1]))
cu = os.environ.get("AGENTERM_CU", "agenterm-cu")
families = []
for v in verbs:
    if v["family"] not in families:
        families.append(v["family"])
print("## Index\n")
print("| verb | scope | family | aliases | summary |")
print("|---|---|---|---|---|")
for v in verbs:
    print(f"| `{v['name']}` | {v.get('grant','')} | {v['family']} | {', '.join('`'+a+'`' for a in v.get('aliases',[])) or '—'} | {v.get('summary','')} |")
for fam in families:
    print(f"\n## {fam}\n")
    for v in [x for x in verbs if x["family"] == fam]:
        print(f"### `{v['name']}`\n")
        ref = subprocess.run([cu, "help", v["name"]], capture_output=True, text=True)
        if ref.returncode != 0:
            raise SystemExit(f"help failed for {v['name']}: {ref.returncode}")
        prose = ref.stderr.strip() or ref.stdout.strip()
        help_lines = {line.strip() for line in prose.splitlines()}
        extra_usage = [line for line in v.get("usage", "").splitlines()
                       if line.strip() and line.strip() not in help_lines]
        if extra_usage:
            print("Additional invocation forms not shown by help:\n")
            print("```text")
            print("\n".join(extra_usage))
            print("```\n")
        if prose:
            print("```text")
            print(prose)
            print("```\n")
PY
} > "$TMP"
# Keep exactly one trailing newline so regenerated references pass the tree's
# diff hygiene check regardless of the final help block's prose spacing.
perl -0pi -e 's/\n+\z/\n/' "$TMP"
mv "$TMP" "$OUT"
echo "gen-cu-verbs-doc: wrote $OUT ($(wc -l < "$OUT") lines)"
